// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function StackStatus(profile: string, region: string, stackName: string): $CancellablePromise<$models.StackInfo> {
    return $Call.ByID(4294726618, profile, region, stackName);
}

export function Whoami(profile: string, region: string): $CancellablePromise<$models.CallerIdentity> {
    return $Call.ByID(1018559761, profile, region);
}
