// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FailedExecutions finds the stack's state machines via CloudFormation, then
 * lists recent FAILED executions on each.
 */
export function FailedExecutions(c: $models.AwsCtx, limit: number): $CancellablePromise<$models.FailedExec[] | null> {
    return $Call.ByID(3207821363, c, limit);
}

/**
 * GetSubscriber reads the full SUB#<email> partition: profile, executions,
 * recent send log, suppression record.
 */
export function GetSubscriber(c: $models.AwsCtx, email: string): $CancellablePromise<$models.SubscriberDetail> {
    return $Call.ByID(4230052049, c, email);
}

/**
 * ListBroadcasts returns the broadcast log (newest first) merged with live
 * counters from STATS#<broadcastId>/COUNTERS — same merge the MCP server does.
 */
export function ListBroadcasts(c: $models.AwsCtx, limit: number): $CancellablePromise<$models.BroadcastRow[] | null> {
    return $Call.ByID(1793789961, c, limit);
}

/**
 * RecentEvents merges the newest engagement events across the given sequence
 * ids (one SequenceIndex query each, newest-first).
 */
export function RecentEvents(c: $models.AwsCtx, sequenceIds: string[] | null, limit: number): $CancellablePromise<$models.EventRow[] | null> {
    return $Call.ByID(3914010203, c, sequenceIds, limit);
}

/**
 * SequenceOverview returns counters + active execution counts for a set of
 * sequence ids (fanned out concurrently — one GetItem + one COUNT query each).
 */
export function SequenceOverview(c: $models.AwsCtx, sequenceIds: string[] | null): $CancellablePromise<$models.SequenceRuntime[] | null> {
    return $Call.ByID(3249395659, c, sequenceIds);
}

/**
 * SequenceSubscribers lists who is currently in a sequence (inverted EXEC rows).
 */
export function SequenceSubscribers(c: $models.AwsCtx, sequenceId: string, limit: number): $CancellablePromise<$models.SeqSubscriberRow[] | null> {
    return $Call.ByID(1180104175, c, sequenceId, limit);
}

/**
 * SequenceTimeSeries buckets a sequence's events per day for the last `days`.
 */
export function SequenceTimeSeries(c: $models.AwsCtx, sequenceId: string, days: number): $CancellablePromise<$models.DayCounts[] | null> {
    return $Call.ByID(1281221276, c, sequenceId, days);
}

/**
 * SesAccountHealth returns quota usage and sandbox status.
 */
export function SesAccountHealth(c: $models.AwsCtx): $CancellablePromise<$models.SesHealth> {
    return $Call.ByID(3717925703, c);
}

/**
 * SubscriberEvents returns a subscriber's engagement timeline (newest first).
 */
export function SubscriberEvents(c: $models.AwsCtx, email: string, limit: number): $CancellablePromise<$models.EventRow[] | null> {
    return $Call.ByID(2745449830, c, email, limit);
}

/**
 * SubscribersByTag lists subscribers via the TAG#<tag> inverted index.
 */
export function SubscribersByTag(c: $models.AwsCtx, tag: string, limit: number): $CancellablePromise<$models.TagRow[] | null> {
    return $Call.ByID(3250756251, c, tag, limit);
}

/**
 * TemplateStats aggregates event counts per template via the TemplateIndex
 * GSI, limited to the last sinceDays. Pages are capped; Truncated is set when
 * the cap was hit so the UI never silently under-reports.
 */
export function TemplateStats(c: $models.AwsCtx, templateKeys: string[] | null, sinceDays: number): $CancellablePromise<$models.TemplateStat[] | null> {
    return $Call.ByID(2711807318, c, templateKeys, sinceDays);
}
