// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AwsCtx carries the project's .env-derived AWS settings on every call — the
 * backend stays stateless.
 */
export interface AwsCtx {
    "profile": string;
    "region": string;
    "tableName": string;
    "eventsTableName": string;
    "stackName": string;
}

export interface BroadcastRow {
    "broadcastId": string;
    "templateKey": string;
    "subject": string;
    "fromEmail": string;
    "sentAt": string;
    "audienceSize": number;
    "counters": Counters;
}

export interface CallerIdentity {
    "account": string;
    "arn": string;
    "userId": string;
    "region": string;
    "profile": string;
    "error": string;
}

export interface Counters {
    "delivery": number;
    "open": number;
    "click": number;
    "bounce": number;
    "complaint": number;
}

export interface DayCounts {
    /**
     * YYYY-MM-DD
     */
    "date": string;
    "delivery": number;
    "open": number;
    "click": number;
    "bounce": number;
    "complaint": number;
}

export interface EventRow {
    "email": string;
    "eventType": string;
    "templateKey": string;
    "sequenceId": string;
    "subject": string;
    "timestamp": string;
}

export interface ExecRow {
    "sequenceId": string;
    "startedAt": string;
    "transactional": boolean;
}

export interface FailedExec {
    "stateMachine": string;
    "name": string;
    "startDate": string;
    "stopDate": string;
}

/**
 * ProjectInfo describes an opened mailshot project. The project folder is the
 * source of truth — this DTO is derived entirely from files on disk.
 */
export interface ProjectInfo {
    "path": string;
    "name": string;
    "hasEnv": boolean;
    "env": { [_ in string]?: string } | null;
    "issues": string[] | null;
    "sequenceCount": number;
}

export interface RecentProject {
    "path": string;
    "name": string;
    "lastOpened": string;
}

export interface RenderResult {
    "ok": boolean;
    "output": string;
}

export interface SendRow {
    "sentAt": string;
    "templateKey": string;
    "sequenceId": string;
    "subject": string;
}

export interface SeqSubscriberRow {
    "email": string;
    "startedAt": string;
    "transactional": boolean;
}

/**
 * SequenceEntry is one sequences/<dir>/sequence.config.ts, evaluated to JSON.
 * Definition is the JSON-serialized SequenceDefinition (frontend parses it —
 * the recursive step type is modeled in TypeScript, not Go). A per-sequence
 * evaluation failure lands in Error so one broken config never hides the rest.
 */
export interface SequenceEntry {
    "dir": string;
    "configPath": string;
    "id": string;
    "definition": string;
    "error": string;
}

export interface SequenceRuntime {
    "sequenceId": string;
    "activeExecutions": number;
    "counters": Counters;
    "error": string;
}

export interface SesHealth {
    "max24HourSend": number;
    "sentLast24Hours": number;
    "maxSendRate": number;
    "sendingEnabled": boolean;
    "productionAccess": boolean;
    "error": string;
}

export interface StackInfo {
    "name": string;
    "status": string;
    "lastUpdated": string;
    "outputs": StackOutput[] | null;
    "error": string;
}

export interface StackOutput {
    "key": string;
    "value": string;
}

export interface SubscriberDetail {
    "found": boolean;

    /**
     * full PROFILE item; frontend separates system columns
     */
    "profileJson": string;
    "executions": ExecRow[] | null;
    "sendLog": SendRow[] | null;

    /**
     * "" or "bounce"/"complaint"
     */
    "suppression": string;
    "error": string;
}

export interface TagRow {
    "email": string;
    "taggedAt": string;
}

/**
 * TemplateEntry pairs a template source file (src/emails/*) with its rendered
 * output (build/<id>/templates/*.html), matched by basename.
 */
export interface TemplateEntry {
    /**
     * basename without extension
     */
    "name": string;

    /**
     * <sequenceId>/<name>
     */
    "templateKey": string;

    /**
     * "" when only a built file exists
     */
    "sourcePath": string;

    /**
     * "" when not rendered yet
     */
    "builtPath": string;

    /**
     * rendered | stale | missing | orphan
     */
    "status": string;
}

export interface TemplateStat {
    "templateKey": string;
    "counters": Counters;
    "truncated": boolean;
    "error": string;
}
