// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * OpenProject validates the folder, loads .env, records it in the recent list
 * and starts the file watcher that emits "project:changed" events.
 */
export function OpenProject(path: string): $CancellablePromise<$models.ProjectInfo> {
    return $Call.ByID(3378515093, path);
}

/**
 * PickProjectFolder opens the native directory picker and returns the chosen
 * path ("" when cancelled).
 */
export function PickProjectFolder(): $CancellablePromise<string> {
    return $Call.ByID(3714248658);
}

export function RecentProjects(): $CancellablePromise<$models.RecentProject[] | null> {
    return $Call.ByID(557920169);
}

/**
 * RefreshProject re-reads the project without touching recents or the watcher.
 */
export function RefreshProject(path: string): $CancellablePromise<$models.ProjectInfo> {
    return $Call.ByID(1550463472, path);
}
