// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSequence(projectPath: string, dir: string): $CancellablePromise<$models.SequenceEntry> {
    return $Call.ByID(389458257, projectPath, dir);
}

export function ListSequences(projectPath: string): $CancellablePromise<$models.SequenceEntry[] | null> {
    return $Call.ByID(3117311842, projectPath);
}
