// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListTemplates scans sources and build output for one sequence. seqDir is the
 * folder name under sequences/; seqID is the config's id (build paths derive
 * from the id, not the folder).
 */
export function ListTemplates(projectPath: string, seqDir: string, seqID: string): $CancellablePromise<$models.TemplateEntry[] | null> {
    return $Call.ByID(2374765718, projectPath, seqDir, seqID);
}

/**
 * OpenInSystemEditor opens a project file in the user's editor: the `code`
 * CLI when available, otherwise the OS default handler for the file type.
 */
export function OpenInSystemEditor(projectPath: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(2124835336, projectPath, filePath);
}

/**
 * ReadFileInProject returns the contents of a file, restricted to paths inside
 * the project directory.
 */
export function ReadFileInProject(projectPath: string, filePath: string): $CancellablePromise<string> {
    return $Call.ByID(3932643603, projectPath, filePath);
}

/**
 * RenderPreview renders a built template's Liquid variables with sample data.
 * dataJSON is a flat JSON object of subscriber variables; unsubscribeUrl gets
 * a placeholder when absent. Rendering uses a Go Liquid engine — parity note:
 * send-time rendering is LiquidJS, which agrees on standard syntax.
 */
export function RenderPreview(projectPath: string, builtPath: string, dataJSON: string): $CancellablePromise<string> {
    return $Call.ByID(764868329, projectPath, builtPath, dataJSON);
}

/**
 * RunRender executes the sequence's own render script (`pnpm --filter <id>
 * render`) in the project directory — the framework-agnostic way to turn
 * whatever source format the project uses into built HTML.
 */
export function RunRender(projectPath: string, seqID: string): $CancellablePromise<$models.RenderResult> {
    return $Call.ByID(4092239868, projectPath, seqID);
}

/**
 * WriteFileInProject saves edited template/config source. Writes are
 * restricted to the sequences/ subtree — the app never writes build output
 * (that's the render script's job) or anything outside the project.
 */
export function WriteFileInProject(projectPath: string, filePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1307837444, projectPath, filePath, content);
}
